name: fingerprintjs
version: 0.0.2
description: Fingerprintjs wrapper for Dart
homepage: https://samihaddad.dev
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.2

dev_dependencies:
  build_runner: ^1.2.0
  build_web_compilers: ^2.9.0
