name: fingerprintjs
version: 0.0.3
description: Fingerprintjs wrapper for Dart - A modern & flexible browser fingerprinting library
homepage: https://samihaddad.dev
repository: https://github.com/samihaddad/dart-fingerprintjs
issue_tracker: https://github.com/samihaddad/dart-fingerprintjs/issues

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.2

dev_dependencies:
  build_runner: ^1.2.0
  build_web_compilers: ^2.9.0
